repos:
  - repo: local
    hooks:
      - id: format-codes
        name: format codes
        entry: uv run python manager.py fmt
        language: unsupported
        files: ^.*\.(?:cpp|hpp|py)$
      - id: replace-chinese-punctuation
        name: replace Chinese punctuation
        entry: python scripts/replace_chinese_punct.py
        language: unsupported
        files: ^src/.*\.(?:cpp|hpp|tex|md|py|sh|yml)$
  - repo: https://github.com/PyCQA/isort
    rev: 9.0.0a3
    hooks:
      - id: isort
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-illegal-windows-names
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
        exclude: ^test/cpv_local/_data/.*\.out$
      - id: fix-byte-order-marker
      - id: forbid-submodules
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: name-tests-test
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
