src_dir: src
notebook_code_dir: code
notebook_doc_dir: doc_tex
cheatsheet_dir: cheatsheet
test_dir: test_tinplate
notebook_file: notebook
enable_test: false
generate_test_in_notebook: false
notebook:
  chapters:
    util: 杂项
    bit: 位操作
    ds: 数据结构
    geo2d: 二维计算几何
    graph: 图论
    math: 数学
    poly: 多项式
    str: 字符串
  sections:
    util:
    - main: 缺省源
      code_ext: cpp
      test_ext: cpp
    - util: 共同依赖
      code_ext: hpp
      test_ext: cpp
    bit:
    - bceil: std::bit_ceil
      code_ext: hpp
      test_ext: cpp
    - bfloor: std::bit_floor
      code_ext: hpp
      test_ext: cpp
    - bwidth: std::bit_width
      code_ext: hpp
      test_ext: cpp
    - cntl0: std::countl_zero
      code_ext: hpp
      test_ext: cpp
    - cntl1: std::countl_one
      code_ext: hpp
      test_ext: cpp
    - cntr0: std::countr_zero
      code_ext: hpp
      test_ext: cpp
    - cntr1: std::countr_one
      code_ext: hpp
      test_ext: cpp
    - popcnt: std::popcount
      code_ext: hpp
      test_ext: cpp
    - rotl: std::rotl
      code_ext: hpp
      test_ext: cpp
    - rotr: std::rotr
      code_ext: hpp
      test_ext: cpp
    ds: null
    geo2d:
    - circle_class: circle_class
      code_ext: hpp
      test_ext: cpp
    - circle: circle
      code_ext: hpp
      test_ext: cpp
    - cvh_class: cvh_class
      code_ext: hpp
      test_ext: cpp
    - cvh: cvh
      code_ext: hpp
      test_ext: cpp
    - dcvh_class: dcvh_class
      code_ext: hpp
      test_ext: cpp
    - dcvh: dcvh
      code_ext: hpp
      test_ext: cpp
    - line_class: line_class
      code_ext: hpp
      test_ext: cpp
    - line: line
      code_ext: hpp
      test_ext: cpp
    - point_class: point_class
      code_ext: hpp
      test_ext: cpp
    - point: point
      code_ext: hpp
      test_ext: cpp
    - polygon_class: polygon_class
      code_ext: hpp
      test_ext: cpp
    - polygon: polygon
      code_ext: hpp
      test_ext: cpp
    - rel_cc: rel_cc
      code_ext: hpp
      test_ext: cpp
    - rel_cp: rel_cp
      code_ext: hpp
      test_ext: cpp
    - rel_cs: rel_cs
      code_ext: hpp
      test_ext: cpp
    - rel_poc: rel_poc
      code_ext: hpp
      test_ext: cpp
    - rel_pop: rel_pop
      code_ext: hpp
      test_ext: cpp
    - triangle_class: triangle_class
      code_ext: hpp
      test_ext: cpp
    - triangle: triangle
      code_ext: hpp
      test_ext: cpp
    - util: util
      code_ext: hpp
      test_ext: cpp
    graph: null
    math:
    - bsgs: bsgs
      code_ext: hpp
      test_ext: cpp
    - crt_mod: crt_mod
      code_ext: hpp
      test_ext: cpp
    - crt: crt
      code_ext: hpp
      test_ext: cpp
    - do_quot: do_quot
      code_ext: hpp
      test_ext: cpp
    - euler_phi_u32: euler_phi_u32
      code_ext: hpp
      test_ext: cpp
    - euler_phi_u64: euler_phi_u64
      code_ext: hpp
      test_ext: cpp
    - exbsgs: exbsgs
      code_ext: hpp
      test_ext: cpp
    - exgcd: exgcd
      code_ext: hpp
      test_ext: cpp
    - exlucas: exlucas
      code_ext: hpp
      test_ext: cpp
    - fact_mod_gen: fact_mod_gen
      code_ext: hpp
      test_ext: cpp
    - gauss_int: gauss_int
      code_ext: hpp
      test_ext: cpp
    - gcd_fp: gcd_fp
      code_ext: hpp
      test_ext: cpp
    - ifact_mod_gen: ifact_mod_gen
      code_ext: hpp
      test_ext: cpp
    - inv_gcd: inv_gcd
      code_ext: hpp
      test_ext: cpp
    - inv_mod_gen: inv_mod_gen
      code_ext: hpp
      test_ext: cpp
    - inverse: inverse
      code_ext: hpp
      test_ext: cpp
    - invseq_mod_gen: invseq_mod_gen
      code_ext: hpp
      test_ext: cpp
    - is_prime: is_prime
      code_ext: hpp
      test_ext: cpp
    - isqrt: isqrt
      code_ext: hpp
      test_ext: cpp
    - leqs_solver: leqs_solver
      code_ext: hpp
      test_ext: cpp
    - linear_mpf_seive: linear_mpf_seive
      code_ext: hpp
      test_ext: cpp
    - linear_mu_seive: linear_mu_seive
      code_ext: hpp
      test_ext: cpp
    - linear_phi_seive: linear_phi_seive
      code_ext: hpp
      test_ext: cpp
    - linear_seive: linear_seive
      code_ext: hpp
      test_ext: cpp
    - linear_sigma_seive: linear_sigma_seive
      code_ext: hpp
      test_ext: cpp
    - lucas_pp: lucas_pp
      code_ext: hpp
      test_ext: cpp
    - lucas: lucas
      code_ext: hpp
      test_ext: cpp
    - mat_det: mat_det
      code_ext: hpp
      test_ext: cpp
    - mat_ge_basic: mat_ge_basic
      code_ext: hpp
      test_ext: cpp
    - mat_ge_euclid: mat_ge_euclid
      code_ext: hpp
      test_ext: cpp
    - mat_ge_swapr_: mat_ge_swapr_
      code_ext: hpp
      test_ext: cpp
    - mat_ge_xor: mat_ge_xor
      code_ext: hpp
      test_ext: cpp
    - mat_inv: mat_inv
      code_ext: hpp
      test_ext: cpp
    - mat_merge_lr: mat_merge_lr
      code_ext: hpp
      test_ext: cpp
    - mat_merge_ud: mat_merge_ud
      code_ext: hpp
      test_ext: cpp
    - mat_pow: mat_pow
      code_ext: hpp
      test_ext: cpp
    - mat_rk: mat_rk
      code_ext: hpp
      test_ext: cpp
    - mat_tr: mat_tr
      code_ext: hpp
      test_ext: cpp
    - mat_trans: mat_trans
      code_ext: hpp
      test_ext: cpp
    - mat: mat
      code_ext: hpp
      test_ext: cpp
    - mcn_mod: mcn_mod
      code_ext: hpp
      test_ext: cpp
    - mint_d31: mint_d31
      code_ext: hpp
      test_ext: cpp
    - mint_d63: mint_d63
      code_ext: hpp
      test_ext: cpp
    - mint_s30: mint_s30
      code_ext: hpp
      test_ext: cpp
    - mint_s63: mint_s63
      code_ext: hpp
      test_ext: cpp
    - mul_mod_s: mul_mod_s
      code_ext: hpp
      test_ext: cpp
    - mul_mod_u: mul_mod_u
      code_ext: hpp
      test_ext: cpp
    - pfactors: pfactors
      code_ext: hpp
      test_ext: cpp
    - proot_u32: proot_u32
      code_ext: hpp
      test_ext: cpp
    - proot_u64: proot_u64
      code_ext: hpp
      test_ext: cpp
    - qpow_mod: qpow_mod
      code_ext: hpp
      test_ext: cpp
    - qpow: qpow
      code_ext: hpp
      test_ext: cpp
    - qresidue: qresidue
      code_ext: hpp
      test_ext: cpp
    - qtetra_mod: qtetra_mod
      code_ext: hpp
      test_ext: cpp
    - rgcd: rgcd
      code_ext: hpp
      test_ext: cpp
    - rpow: rpow
      code_ext: hpp
      test_ext: cpp
    - safe_mod: safe_mod
      code_ext: hpp
      test_ext: cpp
    - spmat: 稀疏矩阵
      code_ext: hpp
      test_ext: cpp
    - spmat_merge_lr: spmat_merge_lr
      code_ext: hpp
      test_ext: cpp
    - spmat_merge_ud: spmat_merge_ud
      code_ext: hpp
      test_ext: cpp
    - mat_charpoly: 矩阵的特征多项式
      code_ext: hpp
      test_ext: cpp
    - mat_uhb: 将矩阵转为上 Hessenberg 矩阵
      code_ext: hpp
      test_ext: cpp
    - mat_hafnian: 矩阵的 hafnian （图的完美匹配计数）
      code_ext: hpp
      test_ext: cpp
    poly:
    - poly: poly
      code_ext: hpp
      test_ext: cpp
    str: null
cheatsheets:
  nt-const: 初等数论常数表
  seqences: 常见数列
  oeis-seq: 常用 OEIS 数列
  decimal: Python Decimal
  formula: 常用公式
default_code_style: common
code_styles:
  C: cpp
  cc: cpp
  cp: cpp
  cpp: cpp
  CPP: cpp
  c++: cpp
  cxx: cpp
  H: cpp
  hh: cpp
  hp: cpp
  h++: cpp
  hpp: cpp
  HPP: cpp
  hxx: cpp
  tex: tex
formatting_commands:
  cpp:
  - clang-format
  - -style=file
  - -i
  - ${filename}
