src_dir: src
notebook_code_dir: code
notebook_doc_dir: doc_tex
cheatsheet_dir: cheatsheet
test_dir: test_tinplate
notebook_file: notebook
enable_test: false
generate_test_in_notebook: false
notebook:
  chapters:
    util: 杂项
    bit: 位操作
    ds: 数据结构
    geo2d: 二维计算几何
    geo3d: 三维计算几何
    graph: 图论
    comb: 组合数学
    math: 数学
    matrix: 矩阵
    conv: 卷积
    poly: 多项式
    str: 字符串
    rand: 随机数与随机化算法
    game: 游戏
    tree: tree
  sections:
    util:
    - main: 缺省源
      code_ext: cpp
      test_ext: cpp
    - util: 共同依赖
      code_ext: hpp
      test_ext: cpp
    - abs_constexpr: abs_constexpr
      code_ext: hpp
      test_ext: cpp
    - fp_const: 一些浮点常数
      code_ext: hpp
      test_ext: cpp
    - fp_comp: 浮点数比较
      code_ext: hpp
      test_ext: cpp
    - fp_range_is_intersect: 判断浮点数区间是否相交
      code_ext: hpp
      test_ext: cpp
    - fp_range_is_in_middle: 判断浮点数是否在浮点数区间中
      code_ext: hpp
      test_ext: cpp
    - base64: Base64
      code_ext: hpp
      test_ext: cpp
    - fp2uint: fp2uint
      code_ext: hpp
      test_ext: cpp
    - hash_splitmix64: Hash splitmix64
      code_ext: hpp
      test_ext: cpp
    - huffman_tree: Huffman 树
      code_ext: hpp
      test_ext: cpp
    - dlx: DLX
      code_ext: hpp
      test_ext: cpp
    - discretization: 离散化
      code_ext: hpp
      test_ext: cpp
    - gray_code: Gray 码
      code_ext: hpp
      test_ext: cpp
    bit:
    - bceil: std::bit_ceil
      code_ext: hpp
      test_ext: cpp
    - bfloor: std::bit_floor
      code_ext: hpp
      test_ext: cpp
    - bwidth: std::bit_width
      code_ext: hpp
      test_ext: cpp
    - cntl0: std::countl_zero
      code_ext: hpp
      test_ext: cpp
    - cntl1: std::countl_one
      code_ext: hpp
      test_ext: cpp
    - cntr0: std::countr_zero
      code_ext: hpp
      test_ext: cpp
    - cntr1: std::countr_one
      code_ext: hpp
      test_ext: cpp
    - log2: log2
      code_ext: hpp
      test_ext: cpp
    - popcnt: std::popcount
      code_ext: hpp
      test_ext: cpp
    - rotl: std::rotl
      code_ext: hpp
      test_ext: cpp
    - rotr: std::rotr
      code_ext: hpp
      test_ext: cpp
    ds:
    - fenwick: 树状数组
      code_ext: hpp
      test_ext: cpp
    - dsu_basic: 并查集
      code_ext: hpp
      test_ext: cpp
    - dsu_pd: 离线可持久化并查集
      code_ext: hpp
      test_ext: cpp
    - dsu_weighted: 带权并查集
      code_ext: hpp
      test_ext: cpp
    - st_array: ST 表 - 数列
      code_ext: hpp
      test_ext: cpp
    - segtree: 线段树
      code_ext: hpp
      test_ext: cpp
    - segtree_old: 旧版线段树
      code_ext: hpp
      test_ext: cpp
    - lichao_segtree: 李超线段树（线段添加、定点最值）
      code_ext: hpp
      test_ext: cpp
    - st_array_2d: 二维 ST 表
      code_ext: hpp
      test_ext: cpp
    - segtree_beats: 吉如一线段树
      code_ext: hpp
      test_ext: cpp
    - weighted_segtree: 权值线段树
      code_ext: hpp
      test_ext: cpp
    - persistent_segtree: 可持久化线段树
      code_ext: hpp
      test_ext: cpp
    - heavy_chain_subdivision: 重链剖分
      code_ext: hpp
      test_ext: cpp
    - fhq_treap: 非旋treap
      code_ext: hpp
      test_ext: cpp
    - fhq_treap_w: 维护区间操作的非旋treap
      code_ext: hpp
      test_ext: cpp
    geo2d:
    - area_cc: area_cc
      code_ext: hpp
      test_ext: cpp
    - area_poc: area_poc
      code_ext: hpp
      test_ext: cpp
    - area_triedges: area_triedges
      code_ext: hpp
      test_ext: cpp
    - circle: circle
      code_ext: hpp
      test_ext: cpp
    - cvh: cvh
      code_ext: hpp
      test_ext: cpp
    - coverage_rect_with_min_area: coverage_rect_with_min_area
      code_ext: hpp
      test_ext: cpp
    - coverage_rect_with_min_circum: coverage_rect_with_min_circum
      code_ext: hpp
      test_ext: cpp
    - ins_hp: ins_hp
      code_ext: hpp
      test_ext: cpp
    - max_area_t: max_area_t
      code_ext: hpp
      test_ext: cpp
    - max_dis_cvh: max_dis_cvh
      code_ext: hpp
      test_ext: cpp
    - min_dis_cvh: min_dis_cvh
      code_ext: hpp
      test_ext: cpp
    - dcvh: dcvh
      code_ext: hpp
      test_ext: cpp
    - extan_cc: extan_cc
      code_ext: hpp
      test_ext: cpp
    - ins_cc: ins_cc
      code_ext: hpp
      test_ext: cpp
    - ins_cl: ins_cl
      code_ext: hpp
      test_ext: cpp
    - intan_cc: intan_cc
      code_ext: hpp
      test_ext: cpp
    - inv_c2c: inv_c2c
      code_ext: hpp
      test_ext: cpp
    - inv_c2l: inv_c2l
      code_ext: hpp
      test_ext: cpp
    - inv_l2c: inv_l2c
      code_ext: hpp
      test_ext: cpp
    - inv_p2p: inv_p2p
      code_ext: hpp
      test_ext: cpp
    - line: line
      code_ext: hpp
      test_ext: cpp
    - dist_pl: dist_pl
      code_ext: hpp
      test_ext: cpp
    - dist_ps: dist_ps
      code_ext: hpp
      test_ext: cpp
    - dist_ss: dist_ss
      code_ext: hpp
      test_ext: cpp
    - ins_ll: ins_ll
      code_ext: hpp
      test_ext: cpp
    - is_ins_ss: is_ins_ss
      code_ext: hpp
      test_ext: cpp
    - is_on_s: is_on_s
      code_ext: hpp
      test_ext: cpp
    - is_on_same_l: is_on_same_l
      code_ext: hpp
      test_ext: cpp
    - proj: proj
      code_ext: hpp
      test_ext: cpp
    - make_c_ppp: make_c_ppp
      code_ext: hpp
      test_ext: cpp
    - make_c_rcc_ex: make_c_rcc_ex
      code_ext: hpp
      test_ext: cpp
    - make_c_rll: make_c_rll
      code_ext: hpp
      test_ext: cpp
    - make_c_rpl: make_c_rpl
      code_ext: hpp
      test_ext: cpp
    - make_c_rpp: make_c_rpp
      code_ext: hpp
      test_ext: cpp
    - min_cover_c: min_cover_c
      code_ext: hpp
      test_ext: cpp
    - point: point
      code_ext: hpp
      test_ext: cpp
    - ang2pi_pp: ang2pi_pp
      code_ext: hpp
      test_ext: cpp
    - ang_pp: ang_pp
      code_ext: hpp
      test_ext: cpp
    - cross: cross
      code_ext: hpp
      test_ext: cpp
    - dist_pp: dist_pp
      code_ext: hpp
      test_ext: cpp
    - dist_pp_ch: dist_pp_ch
      code_ext: hpp
      test_ext: cpp
    - dist_pp_ma: dist_pp_ma
      code_ext: hpp
      test_ext: cpp
    - dot: dot
      code_ext: hpp
      test_ext: cpp
    - make_p_polar: make_p_polar
      code_ext: hpp
      test_ext: cpp
    - max_cover_ps: max_cover_ps
      code_ext: hpp
      test_ext: cpp
    - min_dis_ps: min_dis_ps
      code_ext: hpp
      test_ext: cpp
    - point_is_in_middle: point_is_in_middle
      code_ext: hpp
      test_ext: cpp
    - poly_cnt_intp: poly_cnt_intp
      code_ext: hpp
      test_ext: cpp
    - poly_fermatp: poly_fermatp
      code_ext: hpp
      test_ext: cpp
    - poly_massp: poly_massp
      code_ext: hpp
      test_ext: cpp
    - polygon: polygon
      code_ext: hpp
      test_ext: cpp
    - rel_cc: rel_cc
      code_ext: hpp
      test_ext: cpp
    - rel_cp: rel_cp
      code_ext: hpp
      test_ext: cpp
    - rel_cs: rel_cs
      code_ext: hpp
      test_ext: cpp
    - rel_poc: rel_poc
      code_ext: hpp
      test_ext: cpp
    - rel_pop: rel_pop
      code_ext: hpp
      test_ext: cpp
    - sarea_ct: sarea_ct
      code_ext: hpp
      test_ext: cpp
    - tan_cp: tan_cp
      code_ext: hpp
      test_ext: cpp
    - tcenter_ea: tcenter_ea
      code_ext: hpp
      test_ext: cpp
    - tcenter_g: tcenter_g
      code_ext: hpp
      test_ext: cpp
    - tcenter_h: tcenter_h
      code_ext: hpp
      test_ext: cpp
    - tcenter_i: tcenter_i
      code_ext: hpp
      test_ext: cpp
    - tcenter_n: tcenter_n
      code_ext: hpp
      test_ext: cpp
    - tcenter_o: tcenter_o
      code_ext: hpp
      test_ext: cpp
    - tcenter_x: tcenter_x
      code_ext: hpp
      test_ext: cpp
    - triangle: triangle
      code_ext: hpp
      test_ext: cpp
    - argsort: 极角排序
      code_ext: hpp
      test_ext: cpp
    geo3d:
    - point3d: 点
      code_ext: hpp
      test_ext: cpp
    - line3d: 线
      code_ext: hpp
      test_ext: cpp
    - plane: 平面
      code_ext: hpp
      test_ext: cpp
    - dist3_pl: dist3_pl
      code_ext: hpp
      test_ext: cpp
    - sdist3_plp: sdist3_plp
      code_ext: hpp
      test_ext: cpp
    - rel_plp: rel_plp
      code_ext: hpp
      test_ext: cpp
    - polyhedron: 多面体
      code_ext: hpp
      test_ext: cpp
    graph:
    - dijkstra: Dijkstra
      code_ext: hpp
      test_ext: cpp
    comb:
    - exlucas: exlucas
      code_ext: hpp
      test_ext: cpp
    - derange_mod_gen: 错排数序列
      code_ext: hpp
      test_ext: cpp
    - stirling1_row_gen: 第一类 Stirling 数序列（行）
      code_ext: hpp
      test_ext: cpp
    - stirling1_col_gen: 第一类 Stirling 数序列（列）
      code_ext: hpp
      test_ext: cpp
    - stirling2_row_gen: 第二类 Stirling 数序列（行）
      code_ext: hpp
      test_ext: cpp
    - stirling2_col_gen: 第二类 Stirling 数序列（列）
      code_ext: hpp
      test_ext: cpp
    - bell_gen: Bell 数序列
      code_ext: hpp
      test_ext: cpp
    - partition_gen: 划分数序列
      code_ext: hpp
      test_ext: cpp
    - fact_mod_gen: fact_mod_gen
      code_ext: hpp
      test_ext: cpp
    - mcn_mod: mcn_mod
      code_ext: hpp
      test_ext: cpp
    - ifact_mod_gen: ifact_mod_gen
      code_ext: hpp
      test_ext: cpp
    - inv_mod_gen: inv_mod_gen
      code_ext: hpp
      test_ext: cpp
    - lucas_pp: lucas_pp
      code_ext: hpp
      test_ext: cpp
    - lucas: lucas
      code_ext: hpp
      test_ext: cpp
    - invseq_mod_gen: invseq_mod_gen
      code_ext: hpp
      test_ext: cpp
    - pows_mod_gen: pows_mod_gen
      code_ext: hpp
      test_ext: cpp
    - bernoulli_gen: Bernoulli 数序列
      code_ext: hpp
      test_ext: cpp
    - stirling1_smallp: 第一类 Stirling 数（小模数）
      code_ext: hpp
      test_ext: cpp
    - stirling2_smallp: 第二类 Stirling 数（小模数）
      code_ext: hpp
      test_ext: cpp
    math:
    - barrett: Barrett 模乘法
      code_ext: hpp
      test_ext: cpp
    - bsgs: bsgs
      code_ext: hpp
      test_ext: cpp
    - crt_mod: crt_mod
      code_ext: hpp
      test_ext: cpp
    - crt: crt
      code_ext: hpp
      test_ext: cpp
    - do_quot: do_quot
      code_ext: hpp
      test_ext: cpp
    - euler_phi_u32: euler_phi_u32
      code_ext: hpp
      test_ext: cpp
    - euler_phi_u64: euler_phi_u64
      code_ext: hpp
      test_ext: cpp
    - exbsgs: exbsgs
      code_ext: hpp
      test_ext: cpp
    - exgcd: exgcd
      code_ext: hpp
      test_ext: cpp
    - gauss_int: gauss_int
      code_ext: hpp
      test_ext: cpp
    - gcd_fp: gcd_fp
      code_ext: hpp
      test_ext: cpp
    - inv_gcd: inv_gcd
      code_ext: hpp
      test_ext: cpp
    - inverse: inverse
      code_ext: hpp
      test_ext: cpp
    - is_prime: is_prime
      code_ext: hpp
      test_ext: cpp
    - isqrt: isqrt
      code_ext: hpp
      test_ext: cpp
    - linear_mpf_seive: linear_mpf_seive
      code_ext: hpp
      test_ext: cpp
    - linear_mu_seive: linear_mu_seive
      code_ext: hpp
      test_ext: cpp
    - linear_phi_seive: linear_phi_seive
      code_ext: hpp
      test_ext: cpp
    - linear_seive: linear_seive
      code_ext: hpp
      test_ext: cpp
    - linear_sigma_seive: linear_sigma_seive
      code_ext: hpp
      test_ext: cpp
    - mint_d31: mint_d31
      code_ext: hpp
      test_ext: cpp
    - mint_d63: mint_d63
      code_ext: hpp
      test_ext: cpp
    - mint_ds: 不固定模数 modint 的简单实现
      code_ext: hpp
      test_ext: cpp
    - mint_s30: mint_s30
      code_ext: hpp
      test_ext: cpp
    - mint_s63: mint_s63
      code_ext: hpp
      test_ext: cpp
    - mint_ss: 固定模数 modint 的简单实现
      code_ext: hpp
      test_ext: cpp
    - mul_mod_s: mul_mod_s
      code_ext: hpp
      test_ext: cpp
    - mul_mod_u: mul_mod_u
      code_ext: hpp
      test_ext: cpp
    - pfactors: pfactors
      code_ext: hpp
      test_ext: cpp
    - proot_u32: proot_u32
      code_ext: hpp
      test_ext: cpp
    - proot_u64: proot_u64
      code_ext: hpp
      test_ext: cpp
    - qpow_mod: qpow_mod
      code_ext: hpp
      test_ext: cpp
    - qpow: qpow
      code_ext: hpp
      test_ext: cpp
    - qresidue: 二次剩余
      code_ext: hpp
      test_ext: cpp
    - qtetra_mod: qtetra_mod
      code_ext: hpp
      test_ext: cpp
    - rgcd: rgcd
      code_ext: hpp
      test_ext: cpp
    - rpow: rpow
      code_ext: hpp
      test_ext: cpp
    - safe_mod: safe_mod
      code_ext: hpp
      test_ext: cpp
    - simpson: 自适应 Simpson 积分
      code_ext: hpp
      test_ext: cpp
    - romberg: Romberg 积分
      code_ext: hpp
      test_ext: cpp
    - kahan: Kahan 求和
      code_ext: hpp
      test_ext: cpp
    - real_basis: 实数线性基
      code_ext: hpp
      test_ext: cpp
    - xor_basis: 异或线性基
      code_ext: hpp
      test_ext: cpp
    - cantor: Cantor 展开
      code_ext: hpp
      test_ext: cpp
    - cantor_inv: 逆 Cantor 展开
      code_ext: hpp
      test_ext: cpp
    - kth_root: K 次剩余
      code_ext: hpp
      test_ext: cpp
    matrix:
    - mat: mat
      code_ext: hpp
      test_ext: cpp
    - spmat: 稀疏矩阵
      code_ext: hpp
      test_ext: cpp
    - mat_det: mat_det
      code_ext: hpp
      test_ext: cpp
    - mat_ge_basic: mat_ge_basic
      code_ext: hpp
      test_ext: cpp
    - mat_ge_euclid: mat_ge_euclid
      code_ext: hpp
      test_ext: cpp
    - mat_ge_swapr_: mat_ge_swapr_
      code_ext: hpp
      test_ext: cpp
    - mat_ge_xor: mat_ge_xor
      code_ext: hpp
      test_ext: cpp
    - mat_inv: mat_inv
      code_ext: hpp
      test_ext: cpp
    - mat_merge_lr: mat_merge_lr
      code_ext: hpp
      test_ext: cpp
    - mat_merge_ud: mat_merge_ud
      code_ext: hpp
      test_ext: cpp
    - mat_pow: mat_pow
      code_ext: hpp
      test_ext: cpp
    - mat_rk: mat_rk
      code_ext: hpp
      test_ext: cpp
    - mat_tr: mat_tr
      code_ext: hpp
      test_ext: cpp
    - mat_trans: mat_trans
      code_ext: hpp
      test_ext: cpp
    - mat_charpoly: 矩阵的特征多项式
      code_ext: hpp
      test_ext: cpp
    - mat_uhb: 将矩阵转为上 Hessenberg 矩阵
      code_ext: hpp
      test_ext: cpp
    - mat_hafnian: 矩阵的 hafnian （图的完美匹配计数）
      code_ext: hpp
      test_ext: cpp
    - leqs_solver: 求线性方程组的解和解空间
      code_ext: hpp
      test_ext: cpp
    - lfsr_bm: 寻找最短 LFSR
      code_ext: hpp
      test_ext: cpp
    - mat_minpoly_rd: 求矩阵的最小多项式（随机化算法）
      code_ext: hpp
      test_ext: cpp
    - mat_det_rd: 求矩阵的行列式（随机化算法）
      code_ext: hpp
      test_ext: cpp
    - spmat_merge_lr: spmat_merge_lr
      code_ext: hpp
      test_ext: cpp
    - spmat_merge_ud: spmat_merge_ud
      code_ext: hpp
      test_ext: cpp
    conv:
    - conv_3ntt: 卷积（三模 NTT）
      code_ext: hpp
      test_ext: cpp
    - conv_mtt: 卷积（MTT）
      code_ext: hpp
      test_ext: cpp
    - conv_naive: 卷积（暴力）
      code_ext: hpp
      test_ext: cpp
    - conv_ntt: 卷积（NTT）
      code_ext: hpp
      test_ext: cpp
    - fft: 快速 Fourier 变换
      code_ext: hpp
      test_ext: cpp
    - ntt: 数论变换
      code_ext: hpp
      test_ext: cpp
    - karatsuba: Karatsuba 乘法
      code_ext: hpp
      test_ext: cpp
    - wht: Walsh Hadamard 变换
      code_ext: hpp
      test_ext: cpp
    - zt_subset: 子集 Zeta 变换
      code_ext: hpp
      test_ext: cpp
    - zt_supset: 超集 Zeta 变换
      code_ext: hpp
      test_ext: cpp
    - mt_subset: 子集 Mobius 变换
      code_ext: hpp
      test_ext: cpp
    - mt_supset: 超集 Mobius 变换
      code_ext: hpp
      test_ext: cpp
    - conv_subset: 子集卷积
      code_ext: hpp
      test_ext: cpp
    - conv_and: 卷积（并）
      code_ext: hpp
      test_ext: cpp
    - conv_or: 卷积（交）
      code_ext: hpp
      test_ext: cpp
    - conv_xor: 卷积（异或）
      code_ext: hpp
      test_ext: cpp
    poly:
    - polydata_d: polydata_d
      code_ext: hpp
      test_ext: cpp
    - polydata_s: polydata_s
      code_ext: hpp
      test_ext: cpp
    - poly: poly
      code_ext: hpp
      test_ext: cpp
    - poly_acos: 多项式 acos
      code_ext: hpp
      test_ext: cpp
    - poly_asin: 多项式 asin
      code_ext: hpp
      test_ext: cpp
    - poly_atan: 多项式 atan
      code_ext: hpp
      test_ext: cpp
    - poly_cos: 多项式 cos
      code_ext: hpp
      test_ext: cpp
    - poly_czt: 多项式 Chirp-Z 变换
      code_ext: hpp
      test_ext: cpp
    - poly_deriv: 多项式导数
      code_ext: hpp
      test_ext: cpp
    - poly_div: 多项式整除
      code_ext: hpp
      test_ext: cpp
    - poly_divmod: 多项式除法 & 取模
      code_ext: hpp
      test_ext: cpp
    - poly_exp: 多项式 exp
      code_ext: hpp
      test_ext: cpp
    - poly_int: 多项式积分
      code_ext: hpp
      test_ext: cpp
    - poly_interp: 快速插值
      code_ext: hpp
      test_ext: cpp
    - poly_inv: 多项式逆函数
      code_ext: hpp
      test_ext: cpp
    - poly_ln: 多项式 ln
      code_ext: hpp
      test_ext: cpp
    - poly_mpe: 多项式多点求值
      code_ext: hpp
      test_ext: cpp
    - poly_pow: 多项式 pow
      code_ext: hpp
      test_ext: cpp
    - poly_shl: 多项式左移
      code_ext: hpp
      test_ext: cpp
    - poly_shr: 多项式右移
      code_ext: hpp
      test_ext: cpp
    - poly_sin: 多项式 sin
      code_ext: hpp
      test_ext: cpp
    - poly_sqrt: 多项式 sqrt
      code_ext: hpp
      test_ext: cpp
    - poly_tan: 多项式 tan
      code_ext: hpp
      test_ext: cpp
    - poly_tsh: 多项式单点平移
      code_ext: hpp
      test_ext: cpp
    - poly_ode: 多项式 ODE
      code_ext: hpp
      test_ext: cpp
    - polysp: 多项式转稀疏多项式
      code_ext: hpp
      test_ext: cpp
    - polysp_inv: 稀疏多项式逆函数
      code_ext: hpp
      test_ext: cpp
    - polysp_ln: 稀疏多项式 ln
      code_ext: hpp
      test_ext: cpp
    - polysp_exp: 稀疏多项式 exp
      code_ext: hpp
      test_ext: cpp
    - polysp_pow: 稀疏多项式 pow
      code_ext: hpp
      test_ext: cpp
    str:
    - z_func: Z 函数（扩展 KMP）
      code_ext: hpp
      test_ext: cpp
    - manacher: Manacher
      code_ext: hpp
      test_ext: cpp
    - hash_substr_1mod: 单模子串 Hash
      code_ext: hpp
      test_ext: cpp
    - hash_substr_2mod: 双模子串 Hash
      code_ext: hpp
      test_ext: cpp
    - suffix_array: 后缀数组
      code_ext: hpp
      test_ext: cpp
    - suffix_automaton: 后缀自动机
      code_ext: hpp
      test_ext: cpp
    rand:
    - gen: 随机数生成辅助类
      code_ext: hpp
      test_ext: cpp
    - simulated_annealing: 模拟退火
      code_ext: hpp
      test_ext: cpp
    game:
    - sudoku: 数独求解
      code_ext: hpp
      test_ext: cpp
    tree:
    - tree: 树
      code_ext: hpp
      test_ext: cpp
cheatsheets:
  nt-const: 初等数论常数表
  seqences: 常见数列
  oeis-seq: 常用 OEIS 数列
  decimal: Python Decimal
  formula: 常用公式
default_code_style: common
code_styles:
  C: cpp
  cc: cpp
  cp: cpp
  cpp: cpp
  CPP: cpp
  c++: cpp
  cxx: cpp
  H: cpp
  hh: cpp
  hp: cpp
  h++: cpp
  hpp: cpp
  HPP: cpp
  hxx: cpp
  tex: tex
formatting_commands:
  cpp:
  - clang-format
  - -style=file
  - -i
  - ${filename}
