[[languages.cpp.environments]]
CXX = "g++"
CXXFLAGS = ["-std=c++17", "-g", "-Wall", "-Wextra", "-fsanitize=undefined", "-fsanitize=address", "-D_GLIBCXX_DEBUG"]

[[languages.cpp.environments]]
CXX = "clang++"
CXXFLAGS = ["-std=c++17", "-g", "-Wall", "-Wextra", "-fsanitize=undefined", "-fsanitize=address", "-D_GLIBCXX_DEBUG"]
