[[languages.cpp.environments]]
CXX = "g++-14"
CXXFLAGS = ["-std=gnu++20", "-O2", "-ftrapv", "-fsanitize=address,undefined,leak"]

[[languages.cpp.environments]]
CXX = "g++"
CXXFLAGS = ["-std=gnu++20", "--coverage", "-fprofile-abs-path"]
