[languages.cpp]
read_macros = false

[[languages.cpp.environments]]
CXX = "verify-g++"
CXXFLAGS = ["-std=gnu++20", "-O2", "-ftrapv", "-fsanitize=address,undefined,leak"]

[[languages.cpp.environments]]
CXX = "coverage-g++"
CXXFLAGS = ["-std=gnu++20", "--coverage", "-fprofile-abs-path"]
