name: Build & Release

on:
  push:
    branches:
      - master
    paths:
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/**'
      - 'libs/**'
      - 'src/**'
      - '*.bib'
      - '*.cls'
      - '*.py'
      - '*.tex'
      - '*.typ'
  pull_request:
    branches:
      - master
    paths:
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/**'
      - 'libs/**'
      - 'src/**'
      - '*.bib'
      - '*.cls'
      - '*.py'
      - '*.tex'
      - '*.typ'
  workflow_dispatch:
    inputs:
      ignore_font_cache:
        type: boolean
        default: false

jobs:
  build-tex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.12'
          version: "latest"
      - name: Install Python dependencies
        run: uv sync --frozen
      - name: Generate TeX files
        run: |
          uv run python manager.py -l DEBUG doc -t tex
      - name: Download fonts
        run: bash .github/ci-scripts/download-fonts.sh
      - name: Build the LaTeX document
        id: build-latex
        uses: xu-cheng/latex-action@v4
        with:
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          args: "-pdf -file-line-error -halt-on-error -interaction=nonstopmode -8bit"
          extra_system_packages: |
            unzip
            wget
            python3
            py3-pip
            py3-pygments
            inkscape
            font-noto
            font-noto-cjk
          pre_compile: |
            cp -r .cp-lib/fonts/* /usr/share/fonts
            fc-cache -f
          root_file: notebook.tex
      - name: Upload PDF to artifacts
        uses: actions/upload-artifact@v7
        with:
          name: notebook-tex
          path: notebook-tex.pdf

  build-typ:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
      - name: Install Python dependencies
        run: uv sync --frozen
      - name: Generate Typst files
        run: |
          uv run python manager.py -l DEBUG doc -t typ
      - name: Download fonts
        run: bash .github/ci-scripts/download-fonts.sh
      - name: Install fonts
        run: |
          sudo apt-get install -y fonts-noto fonts-noto-cjk
          cp -r .cp-lib/fonts/* /usr/share/fonts
          fc-cache
      - name: Install Typst
        uses: typst-community/setup-typst@v4
      - name: Build the Typst document
        run: typst compile notebook.typ notebook-typst.pdf
      - name: Upload PDF to artifacts
        uses: actions/upload-artifact@v7
        with:
          name: notebook-typst
          path: notebook-typst.pdf

  pack-include:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.12'
          version: "latest"
      - name: Install Python dependencies
        run: uv sync --frozen
      - name: Copying C++ header files
        run: uv run python manager.py -l DEBUG pack
      - name: Upload LaTeX logs to artifacts
        uses: actions/upload-artifact@v7
        with:
          name: cpp-header
          path: .cp-lib/include

  fast-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.12'
          version: "latest"
      - name: Install Python dependencies
        run: uv sync --frozen
      - name: Run fast test
        run: |
          uv run python manager.py -l DEBUG verify

  release-all:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-tex, build-typ, pack-include, fast-test]
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: artifacts
          merge-multiple: true

      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "${{ github.ref_name }}" artifacts/*
