name: verify
on:
  push:
    branches:
      - master
    paths:
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/**'
      - '.competitive-verifier/**'
      - 'libs/**'
      - 'src/**'
      - 'test/**'
  pull_request:
    branches:
      - master
    paths:
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/**'
      - '.competitive-verifier/**'
      - 'libs/**'
      - 'src/**'
      - 'test/**'
  workflow_dispatch:
    inputs:
      ignore_prev_result:
        type: boolean
        default: false
      cleanup_before_verify:
        type: boolean
        default: false

permissions:
  contents: read

concurrency:
  group: ${{ github.head_ref || 'x' }}-${{ github.workflow }}-${{ github.ref }}-verify
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
      - name: Install competitive-verifier
        run: uv sync --frozen --group verify
      - name: Add uv virtualenv binaries to PATH
        run: echo "${{ github.workspace }}/.venv/bin" >> $GITHUB_PATH
      - name: Create g++ wrapper commands
        shell: bash
        run: bash .github/ci-scripts/create-gpp-wrappers.sh

      - name: oj-resolve
        uses: competitive-verifier/actions/oj-resolve@v2
        with:
          output-path: verify_files.json
          include: |
                src/
                test/cpv
                test/cpv_local
          exclude: |
                src/_*
          config: .competitive-verifier/config.toml
      - name: parse-doxygen
        uses: competitive-verifier/actions/parse-doxygen@v2
        with:
          verify-files: verify_files.json

      - name: Upload verify_files.json
        uses: competitive-verifier/actions/upload-verify-artifact@v2
        with:
          file: verify_files.json

      - name: Check bundled
        id: test-bundled
        run: |
          echo "count=$(find .competitive-verifier/bundled/ -type f | wc -l)" >> $GITHUB_OUTPUT
      - name: Upload bundled
        uses: actions/upload-artifact@v7
        if: steps.test-bundled.outputs.count > 0
        with:
          name: Bundled
          path: .competitive-verifier/bundled

      - name: Restore cached verify results
        if: ${{ !inputs.ignore_prev_result }}
        uses: actions/cache/restore@v5
        id: restore-cached-results
        with:
          path: ${{ github.workspace }}/merged-result.json
          key: verify-merged-${{ github.sha }}
          restore-keys: |
            verify-merged-
      - name: Upload previous verify results
        if: ${{ !inputs.ignore_prev_result && steps.restore-cached-results.outputs.cache-hit }}
        uses: actions/upload-artifact@v7
        with:
          name: Previous-merged-result
          path: ${{ github.workspace }}/merged-result.json

      - name: Delegate verify subtasks
        shell: bash
        run: |
          uv run python cpv_patch.py \
            -l DEBUG delegate \
              -f "src/* test/cpv/* test/cpv_local/* !src/_*" \
              -v verify_files.json \
              ${{ format(!inputs.ignore_prev_result && steps.restore-cached-results.outputs.cache-hit && '-m {0}', 'merged-result.json') }} \
              -t $SPLIT_SIZE \
              -d .cp-lib/verify-list
        env:
          SPLIT_SIZE: 37
      - name: Upload schedule
        uses: actions/upload-artifact@v7
        with:
          name: Verify-schedule
          path: .cp-lib/verify-list

  verify:
    runs-on: ubuntu-latest
    needs: [setup]
    env:
      SPLIT_SIZE: 37
    strategy:
      matrix:
        # prettier-ignore
        index:
          [ "0",  "1",  "2",  "3",  "4",  "5",  "6",  "7",  "8",  "9",
           "10", "11", "12", "13", "14", "15", "16", "17", "18", "19",
           "20", "21", "22", "23", "24", "25", "26", "27", "28", "29",
           "30", "31", "32", "33", "34", "35", "36"]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2147483647
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
      - name: Install competitive-verifier
        run: uv sync --frozen --group verify
      - name: Add uv virtualenv binaries to PATH
        run: echo "${{ github.workspace }}/.venv/bin" >> $GITHUB_PATH
      - name: Create g++ wrapper commands
        shell: bash
        run: bash .github/ci-scripts/create-gpp-wrappers.sh

      - name: Download verify_files.json
        uses: competitive-verifier/actions/download-verify-artifact@v2
        with:
          set-env: false
      - name: Download schedule
        uses: actions/download-artifact@v8
        with:
          name: Verify-schedule
          path: .cp-lib/verify-list
      - name: Reset $COMPETITIVE_VERIFY_FILES_PATH
        shell: bash
        run: |
          echo "COMPETITIVE_VERIFY_FILES_PATH=.cp-lib/verify-list/${{ matrix.index }}.json" >> $GITHUB_ENV

      - name: Get storage information
        run: bash .github/ci-scripts/print-storage-info.sh

      - name: Clean up
        if: ${{ inputs.cleanup_before_verify }}
        run: bash .github/ci-scripts/cleanup-runner.sh

      - name: Get storage information after cleaning up
        if: ${{ inputs.cleanup_before_verify }}
        run: bash .github/ci-scripts/print-storage-info.sh

      - name: Verify
        uses: competitive-verifier/actions/verify@v2
        with:
          destination: ${{runner.temp}}/result.json
          timeout: 14400
          tle: 180
        env:
          YUKICODER_TOKEN: ${{secrets.YUKICODER_TOKEN}}

      - name: Get storage information after verify
        run: bash .github/ci-scripts/print-storage-info.sh

      - name: Collect gcov files into _gcov
        shell: bash
        run: bash .github/ci-scripts/collect-gcov.sh

      - name: Upload result artifact
        uses: actions/upload-artifact@v7
        with:
          name: Result-${{ matrix.index }}
          path: ${{runner.temp}}/result.json
      - name: Upload gcov result artifact
        uses: actions/upload-artifact@v7
        with:
          name: Gcov-result-${{ matrix.index }}
          path: _gcov

  docs-and-check:
    runs-on: ubuntu-latest
    needs: [verify]
    outputs:
      upload-pages: ${{ steps.upload-pages.outcome == 'success' }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2147483647
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
      - name: Install competitive-verifier
        run: uv sync --frozen --group verify
      - name: Add uv virtualenv binaries to PATH
        run: echo "${{ github.workspace }}/.venv/bin" >> $GITHUB_PATH

      - name: Download verify_files.json and all artifacts
        id: all-artifacts
        uses: competitive-verifier/actions/download-verify-artifact@v2
        with:
          download-all: true
          artifact-root: .artifacts/

      - name: Restore cached gcov results
        if: ${{ !inputs.ignore_prev_result }}
        uses: actions/cache/restore@v5
        id: restore-cached-gcov
        with:
          path: _gcov
          key: verify-gcov-${{ github.sha }}
          restore-keys: |
            verify-gcov-

      - name: Collect gcov files into _gcov
        shell: bash
        run: bash .github/ci-scripts/collect-gcov.sh
        env:
          IGNORE_PREV_RESULT: ${{ inputs.ignore_prev_result }}
      - name: Build C++ code coverage report pages
        shell: bash
        run: bash .github/ci-scripts/build-cpp-coverage-pages.sh

      - name: Extract bundled
        shell: bash
        run: |
          rm -rf .competitive-verifier/bundled
          if test -d "$SRCDIR"; then
            mkdir -p .competitive-verifier/
            mv "$SRCDIR" .competitive-verifier/bundled
          else
            echo "$SRCDIR does not exist."
          fi
        env:
          SRCDIR: .artifacts/Bundled

      - name: Merge results
        uses: competitive-verifier/actions/merge-result@v2
        with:
          result-files: ${{ steps.all-artifacts.outputs.artifacts-root }}/Result-*/result.json
          output-path: ${{github.workspace}}/merged-result.json
      - name: Docs
        uses: competitive-verifier/actions/docs@v2
        with:
          verify-result: ${{github.workspace}}/merged-result.json
          destination: _jekyll
          write-summary: true

      - name: Upload merged result artifact
        uses: actions/upload-artifact@v7
        with:
          name: Merged-result
          path: ${{github.workspace}}/merged-result.json
      - name: Save merged result cache
        if: ${{ contains(fromJSON('["push", "workflow_dispatch"]'), github.event_name) }}
        uses: actions/cache/save@v5
        with:
          path: ${{ github.workspace }}/merged-result.json
          key: verify-merged-${{ github.sha }}

      - name: Save gcov cache
        if: ${{ contains(fromJSON('["push", "workflow_dispatch"]'), github.event_name) }}
        uses: actions/cache/save@v5
        with:
          path: _gcov
          key: verify-gcov-${{ github.sha }}

      - name: Patch pages doc
        run: uv run python cpv_patch.py -l DEBUG doc -s src -j _jekyll
      - name: Upload page src
        uses: actions/upload-artifact@v7
        with:
          name: page-source
          path: _jekyll

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: _jekyll
          destination: _site
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Upload artifact
        id: upload-pages
        uses: actions/upload-pages-artifact@v5
        with:
          path: _site

      - name: Check
        uses: competitive-verifier/actions/check@v2
        with:
          verify-result: ${{ steps.all-artifacts.outputs.artifacts-root }}/Result-*/result.json

  deploy:
    if: ${{ contains(fromJSON('["push", "workflow_dispatch"]'), github.event_name) && (success() || failure()) && github.ref == 'refs/heads/master' && needs.docs-and-check.outputs.upload-pages == 'true' }}
    needs: docs-and-check
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
